In [2]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

import utils.data_processing_bronze_table
import utils.data_processing_silver_table
import utils.data_processing_gold_table

## Set up PySpark Session

In [3]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/12 07:55:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

## Set Up Config

In [4]:
# set up config
snapshot_date_str = "2023-01-01"

start_date_str = "2023-01-01"
end_date_str = "2024-12-01"

In [5]:
# generate list of dates to process
def generate_first_of_month_dates(start_date_str, end_date_str):
    # Convert the date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    # List to store the first of month dates
    first_of_month_dates = []

    # Start from the first of the month of the start_date
    current_date = datetime(start_date.year, start_date.month, 1)

    while current_date <= end_date:
        # Append the date in yyyy-mm-dd format
        first_of_month_dates.append(current_date.strftime("%Y-%m-%d"))
        
        # Move to the first of the next month
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return first_of_month_dates

dates_str_lst = generate_first_of_month_dates(start_date_str, end_date_str)
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01']

## Inspect Data

In [6]:
# Inspect all 4 source CSVs
for name, path in [
    ("lms_loan_daily", "data/data/lms_loan_daily.csv"),
    ("feature_clickstream","data/data/feature_clickstream.csv"),
    ("features_financials","data/data/features_financials.csv"),
    ("features_attributes","data/data/features_attributes.csv")]:
    print(name)
    display(pd.read_csv(path))

lms_loan_daily

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,0,10000,0.0,0.0,0.0,10000.0,2023-05-01
1,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,1,10000,1000.0,1000.0,0.0,9000.0,2023-06-01
2,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2023-07-01
3,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,3,10000,1000.0,0.0,1000.0,8000.0,2023-08-01
4,CUS_0x1000_2023_05_01,CUS_0x1000,2023-05-01,10,4,10000,1000.0,2000.0,0.0,6000.0,2023-09-01
...,...,...,...,...,...,...,...,...,...,...,...
137495,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2024-09-01
137496,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,7,10000,1000.0,1000.0,0.0,3000.0,2024-10-01
137497,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,8,10000,1000.0,1000.0,0.0,2000.0,2024-11-01
137498,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01
137499,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,10,10000,1000.0,1000.0,0.0,0.0,2025-01-01

feature_clickstream

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,63,118,80,121,55,193,111,112,-101,83,...,-16,-81,-126,114,35,85,-73,76,CUS_0x1037,2023-01-01
1,-108,182,123,4,-56,27,25,-6,284,222,...,-14,-96,200,35,130,94,111,75,CUS_0x1069,2023-01-01
2,-13,8,87,166,214,-98,215,152,129,139,...,26,86,171,125,-130,354,17,302,CUS_0x114a,2023-01-01
3,-85,45,200,89,128,54,76,51,61,139,...,172,96,174,163,37,207,180,118,CUS_0x1184,2023-01-01
4,55,120,226,-86,253,97,107,68,103,126,...,76,43,183,159,-26,104,118,184,CUS_0x1297,2023-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215371,414,22,72,57,142,192,11,139,24,63,...,179,91,20,189,-35,-19,15,66,CUS_0xdf6,2024-12-01
215372,116,-124,-108,212,-21,227,146,112,186,-65,...,38,226,319,98,9,152,17,14,CUS_0xe23,2024-12-01
215373,237,-3,-49,375,144,41,-170,324,19,266,...,7,102,64,191,124,220,231,75,CUS_0xe4e,2024-12-01
215374,5,67,211,83,207,-41,325,14,-18,41,...,109,266,28,157,131,116,101,131,CUS_0xedd,2024-12-01
215375,196,11,115,94,167,227,119,255,32,96,...,120,85,363,74,-26,107,104,186,CUS_0xfe4,2024-12-01

features_financials

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date
0,CUS_0x1000,30625.94,2706.161667,6,5,27,2,"Credit-Builder Loan, and Home Equity Loan",57,26,...,Bad,1562.91,30.077191,10 Years and 9 Months,Yes,42.941090,77.31427572208112,High_spent_Medium_value_payments,400.36080052211616,2023-05-01
1,CUS_0x1009,52312.68_,4250.390000,6,5,17,4,"Not Specified, Home Equity Loan, Credit-Builde...",5,18,...,_,202.68,40.286997,31 Years and 0 Months,Yes,108.366467,58.66019164829086,High_spent_Medium_value_payments,508.01234122645366,2025-01-01
2,CUS_0x100b,113781.38999999998,9549.782500,1,4,1,0,NaN,14,8,...,Good,1030.2,28.592943,15 Years and 10 Months,No,0.000000,617.0792665202719,High_spent_Small_value_payments,597.8989834797281,2024-03-01
3,CUS_0x1011,58918.47,5208.872500,3,3,17,3,"Student Loan, Credit-Builder Loan, and Debt Co...",27,13,...,Standard,473.14,27.829959,15 Years and 10 Months,Yes,123.434939,383.35084463651407,Low_spent_Medium_value_payments,294.1014665671429,2023-11-01
4,CUS_0x1013,98620.98,7962.415000,3,3,6,3,"Student Loan, Debt Consolidation Loan, and Per...",12,9,...,Good,1233.51,26.524864,17 Years and 10 Months,No,228.018084,332.3337079767732,High_spent_Medium_value_payments,485.8897083704929,2023-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,CUS_0xff3,17032.785,1176.398750,0,6,2,3,"Personal Loan, Mortgage Loan, and Auto Loan",13,7_,...,Good,1229.08,26.915577,17 Years and 3 Months,No,33.299764,81.19585741743609,Low_spent_Small_value_payments,293.14425404017936,2024-06-01
12496,CUS_0xff4,25546.26,2415.855000,8,7,14,5_,"Not Specified, Student Loan, Student Loan, Cre...",15,13_,...,Standard,758.44,39.333488,18 Years and 9 Months,Yes,101.328637,189.81586133347676,Low_spent_Medium_value_payments,230.44100130267208,2024-12-01
12497,CUS_0xff6,117639.92,9727.326667,5,6,1,2,"Home Equity Loan, and Auto Loan",-3,7,...,Good,338.3,32.871853,24 Years and 11 Months,No,126.638453,534.0885271982645,Low_spent_Medium_value_payments,592.0056861539196,2024-10-01
12498,CUS_0xffc,60877.17,5218.097500,6,8,27,8,"Credit-Builder Loan, Payday Loan, Not Specifie...",46,14,...,_,1300.13,29.026498,13 Years and 1 Months,Yes,272.809169,46.4256138380274,High_spent_Large_value_payments,442.5749666782518,2024-01-01
12499,CUS_0xffd,41398.44,3749.870000,8,7,13,6,"Auto Loan, Payday Loan, Payday Loan, Mortgage ...",23,11,...,Standard,1701.88,39.916655,18 Years and 9 Months,Yes,182.976649,42.57571978536272,High_spent_Large_value_payments,389.434630761722,2024-03-01

features_attributes

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
0,CUS_0x1000,Alistair Barrf,18,913-74-1218,Lawyer,2023-05-01
1,CUS_0x1009,Arunah,26,063-67-6938,Mechanic,2025-01-01
2,CUS_0x100b,Shirboni,19,#F%$D@*&8,Media_Manager,2024-03-01
3,CUS_0x1011,Schneyerh,44,793-05-8223,Doctor,2023-11-01
4,CUS_0x1013,Cameront,44,930-49-9615,Mechanic,2023-12-01
...,...,...,...,...,...,...
12495,CUS_0xff3,Somervilled,55,#F%$D@*&8,Scientist,2024-06-01
12496,CUS_0xff4,Poornimaf,37,655-05-7666,Entrepreneur,2024-12-01
12497,CUS_0xff6,Shieldsb,19,541-92-8371,Doctor,2024-10-01
12498,CUS_0xffc,Brads,18,226-86-7294,Musician,2024-01-01
12499,CUS_0xffd,Damouniq,30,832-88-8320,Scientist,2024-03-01

## Build Bronze Table lms

In [7]:
# create bronze datalake for lms_loan_daily
bronze_lms_directory = "datamart/bronze/lms/"

if not os.path.exists(bronze_lms_directory):
    os.makedirs(bronze_lms_directory)

In [8]:
# run bronze backfill
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_lms_directory, spark, "lms_loan_daily")

2023-01-01row count: 530
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_01_01.csv
2023-02-01row count: 1031
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_02_01.csv
2023-03-01row count: 1537
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_03_01.csv
2023-04-01row count: 2047
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_04_01.csv
2023-05-01row count: 2568
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_05_01.csv
2023-06-01row count: 3085
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_06_01.csv
2023-07-01row count: 3556
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_07_01.csv
2023-08-01row count: 4037
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_08_01.csv
2023-09-01row count: 4491
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_09_01.csv
2023-10-01row count: 4978
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_10_01.csv
2023-11-01row count: 5469
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_11_01.csv
2023-12-01row count: 5428
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2023_12_01.csv
2024-01-01row count: 5412
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_01_01.csv
2024-02-01row count: 5424
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_02_01.csv
2024-03-01row count: 5425
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_03_01.csv
2024-04-01row count: 5417
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_04_01.csv
2024-05-01row count: 5391
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_05_01.csv
2024-06-01row count: 5418
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_06_01.csv
2024-07-01row count: 5442
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_07_01.csv
2024-08-01row count: 5531
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_08_01.csv
2024-09-01row count: 5537
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_09_01.csv
2024-10-01row count: 5502
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_10_01.csv
2024-11-01row count: 5501
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_11_01.csv
2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_12_01.csv

In [9]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_lms_directory, spark, "lms_loan_daily").toPandas()

2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_lms_loan_daily_2024_12_01.csv

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x100b_2024_03_01,CUS_0x100b,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01
1,CUS_0x102e_2024_04_01,CUS_0x102e,2024-04-01,10,8,10000,1000.0,0.0,6000.0,8000.0,2024-12-01
2,CUS_0x1038_2024_10_01,CUS_0x1038,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
3,CUS_0x103e_2024_12_01,CUS_0x103e,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
4,CUS_0x1048_2024_02_01,CUS_0x1048,2024-02-01,10,10,10000,1000.0,0.0,9000.0,9000.0,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...
5526,CUS_0xfe3_2024_04_01,CUS_0xfe3,2024-04-01,10,8,10000,1000.0,1000.0,0.0,2000.0,2024-12-01
5527,CUS_0xff3_2024_06_01,CUS_0xff3,2024-06-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2024-12-01
5528,CUS_0xff4_2024_12_01,CUS_0xff4,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
5529,CUS_0xff6_2024_10_01,CUS_0xff6,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
5530,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01

## Build Bronze Table Financial

In [10]:
# create bronze datalake for features_financial
bronze_fin_directory = "datamart/bronze/financial/"

if not os.path.exists(bronze_fin_directory):
    os.makedirs(bronze_fin_directory)

In [11]:
# run bronze backfill
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_fin_directory, spark, "features_financials")

2023-01-01row count: 530
saved to: datamart/bronze/financial/bronze_features_financials_2023_01_01.csv
2023-02-01row count: 501
saved to: datamart/bronze/financial/bronze_features_financials_2023_02_01.csv
2023-03-01row count: 506
saved to: datamart/bronze/financial/bronze_features_financials_2023_03_01.csv
2023-04-01row count: 510
saved to: datamart/bronze/financial/bronze_features_financials_2023_04_01.csv
2023-05-01row count: 521
saved to: datamart/bronze/financial/bronze_features_financials_2023_05_01.csv
2023-06-01row count: 517
saved to: datamart/bronze/financial/bronze_features_financials_2023_06_01.csv
2023-07-01row count: 471
saved to: datamart/bronze/financial/bronze_features_financials_2023_07_01.csv
2023-08-01row count: 481
saved to: datamart/bronze/financial/bronze_features_financials_2023_08_01.csv
2023-09-01row count: 454
saved to: datamart/bronze/financial/bronze_features_financials_2023_09_01.csv
2023-10-01row count: 487
saved to: datamart/bronze/financial/bronze_features_financials_2023_10_01.csv
2023-11-01row count: 491
saved to: datamart/bronze/financial/bronze_features_financials_2023_11_01.csv
2023-12-01row count: 489
saved to: datamart/bronze/financial/bronze_features_financials_2023_12_01.csv
2024-01-01row count: 485
saved to: datamart/bronze/financial/bronze_features_financials_2024_01_01.csv
2024-02-01row count: 518
saved to: datamart/bronze/financial/bronze_features_financials_2024_02_01.csv
2024-03-01row count: 511
saved to: datamart/bronze/financial/bronze_features_financials_2024_03_01.csv
2024-04-01row count: 513
saved to: datamart/bronze/financial/bronze_features_financials_2024_04_01.csv
2024-05-01row count: 491
saved to: datamart/bronze/financial/bronze_features_financials_2024_05_01.csv
2024-06-01row count: 498
saved to: datamart/bronze/financial/bronze_features_financials_2024_06_01.csv
2024-07-01row count: 505
saved to: datamart/bronze/financial/bronze_features_financials_2024_07_01.csv
2024-08-01row count: 543
saved to: datamart/bronze/financial/bronze_features_financials_2024_08_01.csv
2024-09-01row count: 493
saved to: datamart/bronze/financial/bronze_features_financials_2024_09_01.csv
2024-10-01row count: 456
saved to: datamart/bronze/financial/bronze_features_financials_2024_10_01.csv
2024-11-01row count: 488
saved to: datamart/bronze/financial/bronze_features_financials_2024_11_01.csv
2024-12-01row count: 515
saved to: datamart/bronze/financial/bronze_features_financials_2024_12_01.csv

In [12]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_fin_directory, spark, "features_financials").toPandas()

2024-12-01row count: 515
saved to: datamart/bronze/financial/bronze_features_financials_2024_12_01.csv

,Customer_ID,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,snapshot_date
0,CUS_0x103e,98690.8,8262.233333,4,6,9,1_,Student Loan,6,17,...,Good,706.96,26.860663,26 Years and 11 Months,No,55.004408,913.4813186573292,Low_spent_Small_value_payments,147.7376071067124,2024-12-01
1,CUS_0x1195,30429.91,2808.825833,4,6,16,2,"Auto Loan, and Auto Loan",22,17,...,Standard,362.48,33.349050,28 Years and 11 Months,No,29.914076,82.87878577514347,Low_spent_Large_value_payments,438.08972109416084,2024-12-01
2,CUS_0x1197,92300.01,7437.667500,2,4,11,3,"Credit-Builder Loan, Not Specified, and Credit...",27,9,...,_,755.17_,26.989787,18 Years and 11 Months,Yes,49236.000000,220.8621525417414,Low_spent_Large_value_payments,581.1567885447394,2024-12-01
3,CUS_0x11e2,44986.55,3689.879167,6,5,11,1,Credit-Builder Loan,0,4,...,Good,753.21,25.586286,20 Years and 0 Months,No,23.267135,43.20363344633164,High_spent_Large_value_payments,542.5171477430948,2024-12-01
4,CUS_0x11ec,14867.69,1005.974167,9,9,18,6,"Debt Consolidation Loan, Student Loan, Persona...",39,15,...,Standard,2344.06,24.344388,17 Years and 2 Months,Yes,55.459604,100.14574834721886,Low_spent_Medium_value_payments,224.99206407779144,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,CUS_0xe6c,125597.52,9367.500187,1,3,12,4,"Debt Consolidation Loan, Not Specified, Studen...",2,9,...,Good,1294.94,30.324257,30 Years and 5 Months,NM,1278.186251,964.5381161830327,Low_spent_Medium_value_payments,763.3982127892344,2024-12-01
511,CUS_0xe99,45461.54,3917.461667,6,3,5,2,"Credit-Builder Loan, and Payday Loan",20,9,...,Standard,647.24,27.264685,16 Years and 9 Months,No,69.318349,42.941001590068666,High_spent_Large_value_payments,519.4868162135749,2024-12-01
512,CUS_0xf55,78443.48_,6358.956667,7,5,23,4,"Personal Loan, Home Equity Loan, Mortgage Loan...",39,19,...,Bad,1527.77,24.704429,15 Years and 10 Months,NM,177.387563,528.7469053018515,Low_spent_Medium_value_payments,209.76119880079318,2024-12-01
513,CUS_0xfd1,78666.56999999999,6485.547500,3,4,17,4,"Not Specified, Personal Loan, Home Equity Loan...",29,10,...,Standard,1498.7,37.831762,22 Years and 5 Months,No,247.851145,252.3461368272953,High_spent_Small_value_payments,408.35746850506007,2024-12-01
514,CUS_0xff4,25546.26,2415.855000,8,7,14,5_,"Not Specified, Student Loan, Student Loan, Cre...",15,13_,...,Standard,758.44,39.333488,18 Years and 9 Months,Yes,101.328637,189.81586133347676,Low_spent_Medium_value_payments,230.44100130267208,2024-12-01

## Build Bronze Table Attributes

In [13]:
# create bronze datalake for features_attributes
bronze_attr_directory = "datamart/bronze/attributes/"

if not os.path.exists(bronze_attr_directory):
    os.makedirs(bronze_attr_directory)

In [14]:
# run bronze backfill
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_attr_directory, spark, "features_attributes")

2023-01-01row count: 530
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_01_01.csv
2023-02-01row count: 501
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_02_01.csv
2023-03-01row count: 506
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_03_01.csv
2023-04-01row count: 510
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_04_01.csv
2023-05-01row count: 521
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_05_01.csv
2023-06-01row count: 517
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_06_01.csv
2023-07-01row count: 471
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_07_01.csv
2023-08-01row count: 481
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_08_01.csv
2023-09-01row count: 454
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_09_01.csv
2023-10-01row count: 487
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_10_01.csv
2023-11-01row count: 491
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_11_01.csv
2023-12-01row count: 489
saved to: datamart/bronze/attributes/bronze_features_attributes_2023_12_01.csv
2024-01-01row count: 485
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_01_01.csv
2024-02-01row count: 518
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_02_01.csv
2024-03-01row count: 511
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_03_01.csv
2024-04-01row count: 513
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_04_01.csv
2024-05-01row count: 491
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_05_01.csv
2024-06-01row count: 498
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_06_01.csv
2024-07-01row count: 505
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_07_01.csv
2024-08-01row count: 543
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_08_01.csv
2024-09-01row count: 493
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_09_01.csv
2024-10-01row count: 456
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_10_01.csv
2024-11-01row count: 488
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_11_01.csv
2024-12-01row count: 515
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_12_01.csv

In [15]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_attr_directory, spark, "features_attributes").toPandas()

2024-12-01row count: 515
saved to: datamart/bronze/attributes/bronze_features_attributes_2024_12_01.csv

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
0,CUS_0x103e,Tim Kellyf,40,155-72-8070,Scientist,2024-12-01
1,CUS_0x1195,Alexk,31,822-48-3629,Manager,2024-12-01
2,CUS_0x1197,Nayako,28,799-23-8283,_______,2024-12-01
3,CUS_0x11e2,Valetkevitchr,34,809-04-1419,Musician,2024-12-01
4,CUS_0x11ec,William Schombergh,34,417-74-2163,Journalist,2024-12-01
...,...,...,...,...,...,...
510,CUS_0xe6c,Doris Frankelh,26,172-24-1577,Entrepreneur,2024-12-01
511,CUS_0xe99,Moone,48,164-90-3178,Mechanic,2024-12-01
512,CUS_0xf55,Tarmo Virkip,39,025-54-8593,Entrepreneur,2024-12-01
513,CUS_0xfd1,Frewy,32,389-55-6408,Architect,2024-12-01
514,CUS_0xff4,Poornimaf,37,655-05-7666,Entrepreneur,2024-12-01

## Build Bronze Table Clickstream

In [16]:
# create bronze datalake for features_clickstream
bronze_click_directory = "datamart/bronze/clickstream/"

if not os.path.exists(bronze_click_directory):
    os.makedirs(bronze_click_directory)

In [17]:
# run bronze backfill
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_click_directory, spark, "feature_clickstream")

2023-01-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_01_01.csv
2023-02-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_02_01.csv
2023-03-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_03_01.csv
2023-04-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_04_01.csv
2023-05-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_05_01.csv
2023-06-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_06_01.csv
2023-07-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_07_01.csv
2023-08-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_08_01.csv
2023-09-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_09_01.csv
2023-10-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_10_01.csv
2023-11-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_11_01.csv
2023-12-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2023_12_01.csv
2024-01-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_01_01.csv
2024-02-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_02_01.csv
2024-03-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_03_01.csv
2024-04-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_04_01.csv
2024-05-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_05_01.csv
2024-06-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_06_01.csv
2024-07-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_07_01.csv
2024-08-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_08_01.csv
2024-09-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_09_01.csv
2024-10-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_10_01.csv
2024-11-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_11_01.csv
2024-12-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv

In [18]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, bronze_click_directory, spark, "feature_clickstream").toPandas()

2024-12-01row count: 8974
saved to: datamart/bronze/clickstream/bronze_feature_clickstream_2024_12_01.csv

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,145,189,109,134,196,-37,101,82,111,24,...,65,249,200,185,-83,-18,-76,30,CUS_0x1037,2024-12-01
1,40,184,187,75,192,146,38,109,353,141,...,-14,193,125,117,215,91,33,255,CUS_0x1069,2024-12-01
2,98,121,180,200,95,48,59,194,76,84,...,167,101,92,185,98,68,-60,116,CUS_0x114a,2024-12-01
3,85,96,19,47,30,39,-32,210,-81,206,...,143,94,139,237,78,187,77,33,CUS_0x1184,2024-12-01
4,98,45,155,56,112,47,52,138,153,225,...,-43,142,121,10,189,110,264,241,CUS_0x1297,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,414,22,72,57,142,192,11,139,24,63,...,179,91,20,189,-35,-19,15,66,CUS_0xdf6,2024-12-01
8970,116,-124,-108,212,-21,227,146,112,186,-65,...,38,226,319,98,9,152,17,14,CUS_0xe23,2024-12-01
8971,237,-3,-49,375,144,41,-170,324,19,266,...,7,102,64,191,124,220,231,75,CUS_0xe4e,2024-12-01
8972,5,67,211,83,207,-41,325,14,-18,41,...,109,266,28,157,131,116,101,131,CUS_0xedd,2024-12-01
8973,196,11,115,94,167,227,119,255,32,96,...,120,85,363,74,-26,107,104,186,CUS_0xfe4,2024-12-01